import Head from "next/head";
import Image from "next/image";
import Header from "@/Components/Header";
import CreateYourOwnPackage from "@/Components/CreateYourOwnPackage";
import { ThemeProvider, createTheme } from "@mui/material/styles";

const theme = createTheme({
  palette: {
    secondary: {
      main: "#000000",
    },
  },
});

export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>beije | Kendi Paketini Oluştur</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <CreateYourOwnPackage />
    </ThemeProvider>
  );
}
